version: "3.8"

services:
  app:
    build: .
    container_name: express-app
    ports:
      - "3002:3002"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
